"""prot

Revision ID: 6742cbd25bea
Revises: ef9410b6f6ee
Create Date: 2021-07-10 15:34:58.411440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6742cbd25bea'
down_revision = 'ef9410b6f6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('protein', sa.Integer(), nullable=True))
    op.add_column('ingredient', sa.Column('fat', sa.Integer(), nullable=True))
    op.add_column('ingredient', sa.Column('carbs', sa.Integer(), nullable=True))
    op.drop_column('ingredient', 'p')
    op.drop_column('ingredient', 'c')
    op.drop_column('ingredient', 'f')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('f', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ingredient', sa.Column('c', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ingredient', sa.Column('p', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('ingredient', 'carbs')
    op.drop_column('ingredient', 'fat')
    op.drop_column('ingredient', 'protein')
    # ### end Alembic commands ###
