"""visible

Revision ID: ffd91b1beb5d
Revises: 6742cbd25bea
Create Date: 2021-07-10 17:00:09.471234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd91b1beb5d'
down_revision = '6742cbd25bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipeingredient', sa.Column('visible', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipeingredient', 'visible')
    # ### end Alembic commands ###
